name: Auto Push on Changes

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
    - name: Check for changes and push
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto push: ${GITHUB_SHA}"
          git push
        fi